# Generated by Django 5.0.1 on 2024-02-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0002_feedback'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table='feedback',
        ),
    ]
