# Generated by Django 5.0.1 on 2024-02-17 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0003_alter_feedback_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='comments',
            new_name='comment',
        ),
    ]
