# Generated by Django 5.0.1 on 2024-02-17 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0004_rename_comments_feedback_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='comment',
            new_name='comments',
        ),
    ]
